services:
  app1:
    image: app1
    environment:
      - APP_NAME=APP1
    ports:
      - "3000:3000"
    networks:
      - my-network

  app2:
    image: app1
    environment:
      - APP_NAME=APP2
    ports:
      - "3001:3000"
    networks:
      - my-network

  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
